### ISSUE TITLE
VSH Bosses have stock weapons

### ISSUE THREAD

**Issue by young11** [Scags/TF2-Jailbreak-Redux#101]
pls help

**Comment by Scags** [comment]
You could've at least given some details. Try the 1.10 branch https://github.com/Scags/TF2-Jailbreak-Redux/tree/sm1.10?files=1

**Comment by young11** [comment]
https://imgur.com/a/95o7tBT
Version 1,4,1 and again

**Comment by young11** [comment]
https://imgur.com/a/NVF9I0Z

**Comment by young11** [comment]
so i found a bug 
if you are in red and you will be a boss you have weapon but if you are in blue and you will be boss you don't have weapons

**Comment by Scags** [comment]
I think I see what's wrong but I won't be able to get around to it for a while. If you can't wait then you can use an older version of the plugin

**Comment by young11** [comment]
so u fixed it?

**Comment by Scags** [comment]
As of now, yes. Sorry about that, I've been quite busy over the last month. Latest under the 'Releases' tab should work as directed.
Closing.

**Comment by Mlodyy1** [comment]
Hello i think this doesn't work
