### ISSUE TITLE
[Suggestion] Multi language support for all phrases 

### ISSUE THREAD

**Issue by wonyoungb** [Scags/TF2-Jailbreak-Redux#102]
When I change this mod to Korean I had a problem with Warden, LR and etc... there is no other way to change in translations file it need to change in scripts.. so I suggest please make all phrases to translation file..
“In result I can’t update plugin because I need to translate again when I update plugin well..”

**Comment by Scags** [comment]
The core plugin, the weapon blocker addon, the repeat annotation addon, and the teamban plugin support translations. However the other addons (Versus Saxton Hale and Prophunt) do not.
I didn't originally plan to do translations for those 2, but it shouldn't be that bad.

**Comment by Scags** [comment]
I'm going to go ahead and close this since Last Request config, as of V2.0, supports custom/translatable names, descriptions, activation messages, etc. All (if not, almost all) messages in the main plugin(s) should have translations.
