### ISSUE TITLE
Issue #101 again

### ISSUE THREAD

**Issue by Mlodyy1** [Scags/TF2-Jailbreak-Redux#104]
hello sorry but this doesn't work

**Comment by wonyoungb** [comment]
I think you should give any little information on it;; 
@Scags is not aladdin
you only doing give some screenshots and saying "it's not working" 
what you are saying right now (include issue #101 ) is kind of bs

**Comment by Scags** [comment]
I also got reports of crashes with the VSH plugin, but it (probably) works with V2.0. Still in a bit of a beta though.

**Comment by Scags** [comment]
I'm quite positive that this is patched, especially now with V2.0.1Beta.
