### ISSUE TITLE
Music audio not work.

### ISSUE THREAD

**Issue by mrnoahfink** [Scags/TF2-Jailbreak-Redux#109]
Since Music not working for pre-made LR and customs lr.

**Comment by mrnoahfink** [comment]
I found out that I am using Jailbreak Beta. I am going reinstall your latest Jailbreak Plugin. But please keep this open if still not work.

**Comment by mrnoahfink** [comment]
Since I use 1.4.7v but unsupported for custom LR like in 2.0.0 Beta. Also I notice that Freeday the Cell Door doesn’t open sometime. And yet music still not working.

**Comment by Scags** [comment]
I highly advise you use at least V2.0. Ignore the "releases" tab for now. I'll finally get around to fixing things up eventually.

**Comment by mrnoahfink** [comment]
I think there issues in jailhandler.sp between 31 to 44 lines were about sound.

**Comment by mrnoahfink** [comment]
should be true not false?

**Comment by mrnoahfink** [comment]
I change to true and still nothing.

**Comment by Scags** [comment]
Probably won't have any effect. Could be just about anything that's tripping it up. Keep in mind I'm entirely taking your word for it as I've not tested LR music.

**Comment by mrnoahfink** [comment]
alright just let me know when you fix it. thx

**Comment by Scags** [comment]
I found a problem, might have been *the* problem. If you were making an LR internally (without using config), the music time length wouldn't have been set properly. That's been fixed with V2.0.3.

**Comment by mrnoahfink** [comment]
For an example for Rocket Day 
-----------------------------------------------------------------

"Rapid Rockets Day"
	{
		"Name"				"Rapid Rockets Day"
		"Description"		"Grants all players a Valve Rocket Launcher next round while turning on friendly fire."
		"Handler"			"LR_RapidRocketsDay"
		"Queue_Announce"	"{NAME} has chosen for everyone to be blown up in the most horrible way possible!"
		"Execute_Cmd"		"sm_giveweapon @all 8018"
		"WeaponsConfig"		"default"
		"Parameters"
		{
			"Disabled"			"0"
			"IsFreedayType"		"0"
			"ActiveRound"		"0"
			"OpenCells"			"1"
			"VoidFreekills"		"1"
			"IsVIPOnly"			"0"
			"DisableMedic"		"1"
			"TimerStatus"		"1"
			"LockWarden"		"1"
			"EnableCriticals"	"1"
			"TimerTime"			"180"
			"KillWeapons"
			{
				"Red"			"0"
				"Blue"			"0"
				"Warden"		"0"
				"Melee"			"0"
			}
			"FriendlyFire"
			{
				"Status"		"1"
				"Timer"			"2.0"
			}
			"UsesPerMap"	"2"
		}
		"Music"
			{
				"Status"			"1"
				"file"				"sound/RocketDay.mp3"
				"time"				"0"
			}
	}

**Comment by mrnoahfink** [comment]
For example where I make Rocket Day with Music. Within Music, the last part of code does look, right?

[Rocket Day CODE.txt](https://github.com/Scags/TF2-Jailbreak-Redux/files/4853865/Rocket.Day.CODE.txt)

**Comment by mrnoahfink** [comment]
I am testing right this moment.

**Comment by Scags** [comment]
It looks fine at a glance. Keep in mind that "time" is the length in seconds of the music file. So if it's 0, the music will play for 0 seconds, over and over and over.

**Comment by mrnoahfink** [comment]
Oh, I think that is my problem ok hold on.

**Comment by mrnoahfink** [comment]
Sounds still not works, however, it seem we getting process I got error like SV_StartSound spamming. like this in console https://github.com/Scags/TF2-Jailbreak-Redux/issues/68 

Yikes

**Comment by Scags** [comment]
I was working with the [MechMercs](https://github.com/Scags/TF2-LRModule-MechMercs) plugin earlier which has music, and that worked fine. Make sure your file path is correct and that you have the file in your server.

You can also try dropping "sound/" from the start of the file path. It should work with either but it can't hurt to try.

**Comment by Scags** [comment]
Now that I think about it, that's exactly what's wrong. I'll work in a fix so either method works later.

**Comment by mrnoahfink** [comment]
Alright time for testing :3

**Comment by mrnoahfink** [comment]
Still not working.

![Annotation 2020-07-01 140118](https://user-images.githubusercontent.com/66857858/86291373-81897c80-bbb4-11ea-8f4a-a20c36cd3461.png)

**Comment by Scags** [comment]
If it's not being precached, that (should) mean that the file does not exist. Try dropping "sound/" off of your file path.

**Comment by mrnoahfink** [comment]
same thing no luck...

**Comment by mrnoahfink** [comment]
It really doesn't read all title of files at all

![Annotation 2020-07-01 175234](https://user-images.githubusercontent.com/66857858/86304499-9bd35280-bbd4-11ea-8aca-0bb7af4dc1ba.png)

**Comment by Scags** [comment]
OH lol. I did an oopsie, just fixed it.

**Comment by mrnoahfink** [comment]
well, I have good news and bad news. Good news is that no longer spamming sv_startsound or no sv_startsound. however, the bad news is that there still no sound. I try to remove sound/ and readd sound/ and still nothing.

**Comment by Scags** [comment]
Make sure that 1: the file is in the proper path on the server and 2: you are downloading the file. When in game, you can check your console and see if an error pops up. It might show something like "Invalid sample rate (0) for my_file.mp3" or something.

If it's being precached, then it probably exists in the server, so there might be an issue with a fastdl if you're using one.

**Comment by mrnoahfink** [comment]
Good point. I am going check my Fastdl.

**Comment by mrnoahfink** [comment]
I relook fast dl and look like the sound is the same as the sound in server folder. And no sound error in console.

**Comment by Scags** [comment]
I don't know what else to tell you, then. You might have music disabled via command or the sound is too quiet to hear. I've no idea since it was working just fine with me yesterday.

**Comment by Stropyt** [comment]
You could try using the sm_play command to find out if the sound is downloaded, all good and working as it should.

**Comment by mrnoahfink** [comment]
this what I got in console also I try do sm_play and same thing

MP3 initialized with no sound cache, this may cause janking. [ rocketday.mp3 ]
Failed to create decoder for MP3 [ rocketday.mp3 ]
MP3 initialized with no sound cache, this may cause janking. [ rocketday.mp3 ]
Failed to create decoder for MP3 [ rocketday.mp3 ]
*** Invalid sample rate (0) for sound 'rocketday.mp3'.

**Comment by Scags** [comment]
Hmmm, then either A: the sound file is not downloaded/isn't in your own game download folder or B: your sound cache got corrupted.

To check A, from what I can see, go to steam/steamapps/common/Team Fortress 2/tf/download/sound/ and see if rocketday.mp3 is there. If it is then it's probably B.

To solve B you'll need to delete your sound cache. I can't remember which one but go to steam/steamapps/common/Team Fortress 2/tf/download/sound/ and delete sound.cache
And steam/steamapps/common/Team Fortress 2/tf/sound/ and delete sound.cache. Then restart TF2 and try it again.

**Comment by mrnoahfink** [comment]
I think the file is corrupted because it still not download anything.

**Comment by mrnoahfink** [comment]
Still not working including changing different music.

**Comment by mrnoahfink** [comment]
wait does fastdl need jailbreak folder for sound? I just wonder incase

**Comment by Scags** [comment]
No, it will download through whatever path is specified in the config.

**Comment by mrnoahfink** [comment]
Imm going closed this because I change my mind to not using music for lr
