### ISSUE TITLE
Last Request not working if map doesn't change

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#11]
I have sm_tf2jr_lr_default set to 0, yet when players get lr, they end up having to choose random only since other options are disabled out. Any idea if this is a bug?

**Comment by unusual917** [comment]
seems like if i set it to a large number it works though

**Comment by Scags** [comment]
Weird, I'm almost positive that if it was set to zero then maxes would be removed. I'll test that tomorrow

**Comment by Scags** [comment]
Ok after testing it worked fine on my end, I guess I fixed it after updating the GitHub last month. Fixed now after the latest update. Closing.
