### ISSUE TITLE
Jailbreak Game Tag

### ISSUE THREAD

**Issue by mrnoahfink** [Scags/TF2-Jailbreak-Redux#114]
Some reason it does not showing game tag for your jailbreak plugin
![Annotation 2020-07-20 183058](https://user-images.githubusercontent.com/66857858/87996287-527d7100-cab7-11ea-86ea-bf5e207a63a7.png)

like this on
![Annotation 2020-07-20 183316](https://user-images.githubusercontent.com/66857858/87996358-88baf080-cab7-11ea-825d-b44a91bf34b3.png)

**Comment by Scags** [comment]
Make sure you are running [SteamWorks](https://forums.alliedmods.net/showthread.php?t=229556).

And of course, if you are compiling the plugin yourself, you need the SteamWorks include file.

**Comment by mrnoahfink** [comment]
Good new and bad new

Good news I have SteamWorks AND Steamtools

bad news still not working...

**Comment by JohnyP41** [comment]
write sm exts list to your console 👍

**Comment by mrnoahfink** [comment]
![Annotation 2020-07-22 124210](https://user-images.githubusercontent.com/66857858/88221227-c63f8b00-cc29-11ea-96f7-992fdeed1d94.png)

**Comment by JohnyP41** [comment]
Ok so SteamWorks AND Steamtools working thats good. Try to restart the server.

**Comment by mrnoahfink** [comment]
I restart and none.

**Comment by JohnyP41** [comment]
write sm plugins list in console

**Comment by Scags** [comment]
This is why I ~~asked~~ mentioned if you were compiling the plugin on your own. That's the only possible explanation since the name should be set and reset every map.

**Comment by mrnoahfink** [comment]
I am not compiling into my plugin if you wondering

**Comment by Scags** [comment]
Then your server might not be hooked up to Steam. Is it a LAN server? Are you hooking it up with a GSLT token? If not, try it. I'm not sure what else to tell you.

**Comment by mrnoahfink** [comment]
It not the LAN server. since there no way doing it. I going to close this.

**Comment by Scags** [comment]
https://forums.alliedmods.net/showpost.php?p=2709420&postcount=780 might be your issue. Can monitor that thread or subscribe and wait.

**Comment by mrnoahfink** [comment]
sure will.

**Comment by mrnoahfink** [comment]
I update my jailbreak and no luck
