### ISSUE TITLE
Saxton Hale. (PROCESS!)

### ISSUE THREAD

**Issue by mrnoahfink** [Scags/TF2-Jailbreak-Redux#115]
The Saxton Hal;e LR

The Saxton Hale showing Error Prop...

**Comment by Scags** [comment]
Make sure you have the proper files downloaded and installed. https://dl.dropboxusercontent.com/s/6ehqx2vy6h9hnpm/hale_server_by_maxxy1996_dbxscwd.zip

Edit: oops thats the new model, https://forums.alliedmods.net/attachment.php?attachmentid=148202&stc=1&d=1442371915 is the one you're looking for unless you've recompiled to include the new model.

**Comment by mrnoahfink** [comment]
I install "second link download" and no long "Error Prop". But...
![Annotation 2020-07-22 113346](https://user-images.githubusercontent.com/66857858/88203463-971c2000-cc0f-11ea-80eb-dd2197e744e1.png)

**Comment by Scags** [comment]
Odd, that's a materials issue. I've double checked my side and everything should be right. Are you absolutely positive that you extracted everything to your server? Should be in `materials/models/player/saxton_test4/`

**Comment by mrnoahfink** [comment]
Sorry for the late reply, Yes I extracted everything right.

**Comment by Scags** [comment]
Are you downloading everything from the server? For example if you pull up that directory in your TF2 download and in your server download, does it download correctly?

**Comment by mrnoahfink** [comment]
I check my "Steam Download TF2 Folder" and it downloads correctly.

**Comment by Scags** [comment]
Ah, yea I see the problem. You might have to wait until I'm done with this next update though.

**Comment by Scags** [comment]
V2.0.4 should fix the Hale texture issue. Try it and see.

**Comment by mrnoahfink** [comment]
Fixed and Saxton Hale is HAPPY!
![saxtonhaleishappy](https://user-images.githubusercontent.com/66857858/89224868-d6972480-d59e-11ea-80f2-9ca2a8d53621.png)
