### ISSUE TITLE
failed to compile

### ISSUE THREAD

**Issue by gladoncio** [Scags/TF2-Jailbreak-Redux#118]
Managed to compile a version of the plugin without errors in the console, however the compiled smx version has errors. Example: The chat is printed multiple times. Please check your .sp

[Link to Foto](https://servilive.cl/images/chat.jpg)

**Comment by Scags** [comment]
Are you compiling from a VPS or a Windows Server? I've had a similar problem when compiling with a Windows 2012R2 VPS. The .sp is fine I can assure you.

**Comment by gladoncio** [comment]
i am compiling in Windows deskstop.

**Comment by Scags** [comment]
Try checking/updating your include/.inc files (morecolors.inc specifically). That might be your issue. Do you have this problem with the .smx that is provided in the repo?

Edit: This might also be an issue with your chat processor plugin, if you have one. You can try checking or updating that too.
Edit Edit: Last thing. If you want, you can attach your .smx here and I can try and decompile it and see what is wrong. Or you can compile it with the "-l" flag to get a .lst file which is a bit more readable.

**Comment by gladoncio** [comment]
I already managed to fix it thanks, the smx version that came worked well just that I was looking to modify it by adding custom sounds etc.
