### ISSUE TITLE
 many take warden at the same time

### ISSUE THREAD

**Issue by gladoncio** [Scags/TF2-Jailbreak-Redux#119]
reviewing I realized that many can access the warden at the same time, also the warden menu does not work at all for users. please check carefully why this happens. opens doors and close doors do not work besides ff. thanks for everything.

**Comment by Scags** [comment]
Are you getting any errors in your server logs? That's the only possible way that multiple people can become Warden. Errors "abort" what is currently happening and some variables may not be set properly.

Door commands rely on what is in the map config file. If that is not set up properly, then doors will not work with Warden menu. Try checking those.

**Comment by gladoncio** [comment]
262/5000
the doors are configured and work with the menu, but only for users with administrator permissions. About the director I modified the plugin and thought it was that, but when testing the official version the same thing happens. ps: it does not generate errors in console

**Comment by Scags** [comment]
Strange, cell doors should not care about administrator permissions. Are you using admin command overrides? The door command in the warden menu "fakes" commands. I.E. Picking "Open Cells" in the menu makes you perform the "sm_open" command. (Or whatever command is in wardenmenu.cfg)

As for multiple wardens, I just don't know how that's possible. My only guess is that somehow, a third party plugin is resetting gamemode properties which lets people become warden again.

I just tested, and it does set the property when it is supposed to. `bWardenExists` is the property that is checked each time someone tries to become a warden.
![](https://imgur.com/GXr3IGU.png)

**Comment by Scags** [comment]
If this issue is still happening feel free to comment on it and I'll reopen this.
