### ISSUE TITLE
I can't translate it

### ISSUE THREAD

**Issue by q1085909155** [Scags/TF2-Jailbreak-Redux#120]
I am a Chinese, why can't I translate your plug-in into Chinese? I have made sure to change the default language to "chi".

**Comment by Scags** [comment]
The plugin's translations work based off of the language of the player. So if you, the player, have "chi" as your language in-game, you will get the Chinese translation. Have you added Chinese translations to the translation file?

The only part of the plugin that does not support translations is PropHunt and VSH.

**Comment by q1085909155** [comment]
Yes, I have added the directory of The Chinese translation file, but it still doesn't work. I don't know why it is like this. I have set everything up, that is, the translation is invalid after Entering the game (I enter the game with "chi").
![QQ截图20200802121905](https://user-images.githubusercontent.com/69096633/89115433-c0b03380-d4ba-11ea-9b23-ca3fc35f2c79.png)
![QQ截图20200802121931](https://user-images.githubusercontent.com/69096633/89115435-c279f700-d4ba-11ea-9cde-6ab84f024561.png)

**Comment by q1085909155** [comment]
Is the translation document "TF2Jail. Sentence "?

**Comment by q1085909155** [comment]
Is the translation document "TF2Jail. Sentence "?

**Comment by Blueberryy** [comment]
Maybe because 'chi' is not exist as language code?
Try to find your language code in this doc https://partner.steamgames.com/doc/store/localization

**Comment by q1085909155** [comment]
What code should I use? You gave me "zh-CN" but the language code in the plug-in is "chi".
![QQ截图20200802152753](https://user-images.githubusercontent.com/69096633/89118053-5fe22480-d4d5-11ea-9190-feb4ade81095.png)
![QQ截图20200802153029](https://user-images.githubusercontent.com/69096633/89118055-61abe800-d4d5-11ea-8bac-e58cbf9f7e96.png)

**Comment by Scags** [comment]
It looks like "chi" is the correct one to pick. But I'm not sure since the translation picture you sent looks correct. As far as I know, the included translations work just fine. I'm not sure what's wrong here.

**Comment by q1085909155** [comment]
What should I do?

**Comment by Scags** [comment]
Have you restarted your server? Try running sm_reload_translations in your server console. Lastly are you sure you put the translation file in the proper folder?

**Comment by q1085909155** [comment]
Yes, I've tried it many times

**Comment by Scags** [comment]
I'm not sure what else to tell you. Translations for the other languages work fine. Are there any errors in your error logs? Lastly, are you *positive* that you filled out the translation file correctly?

![](https://imgur.com/poz8TNV.png)

**Comment by Blueberryy** [comment]
If you can read there is 2 types of Chinese **zh-CN - Simplified** and **zh-TW - Traditional**
Select one that used in translation i guess?

**Comment by q1085909155** [comment]
How do I confirm that I have filled out the translation document correctly

**Comment by Scags** [comment]
What I mean is that are there any mistakes that caused errors to pop up in your error log files. SourceMod parses translations manually and it might catch a missing quotation mark (") or something. You could also try what Blueberryy has said.

**Comment by JohnyP41** [comment]
Here i found something.
http://translator.mitchdempsey.com/phrases/33

Chinese (Simplified) (chi) SourceMod 帮助: 指令信息 
Chinese (Traditional) (zho) SourceMod 幫助: 指令信息

**Comment by Scags** [comment]
Ok looking back I think I see the issue. You're using a different translation file. The file for TF2Jail Redux is tf2jail_redux.phrases.txt. The screencap that you sent looks a lot like regular TF2Jail's translation file.

**Comment by q1085909155** [comment]
Oh, that seems to be the case. Where can I put the Tf2jail_redux.fragment.txt file? I can't find it

> 好吧，回想一下，我想我看到了问题。您正在使用其他翻译文件。TF2Jail Redux的文件是tf2jail_redux.phrases.txt。您发送的屏幕截图非常类似于常规TF2Jail的翻译文件。

Oh, that seems to be the case. Where can I put the Tf2jail_redux.fragment.txt file? I can't find it

**Comment by Scags** [comment]
It should be in the translations folder of what you downloaded.

**Comment by q1085909155** [comment]
Oh, I am so sorry that I forgot to download this file. I have solved the problem. Thank you very much

**Comment by Scags** [comment]
Sure. No problem.
