### ISSUE TITLE
Banning police systems

### ISSUE THREAD

**Issue by q1085909155** [Scags/TF2-Jailbreak-Redux#121]
After I barred a player from entering a guard, he died before entering a guard. Why was his birth place at the guard's birth place

**Comment by q1085909155** [comment]
Let me be clear
1. Block players from entering guards
2. He has died and has been transferred to the prisoner group
He reentered the guard
4. After the new round
5. Counting down to find him at the guard's birth spot

**Comment by q1085909155** [comment]
And I also found that players who had been barred from the game were re-entering the game after quitting. His limitations have disappeared

**Comment by JohnyP41** [comment]
You should try older version of teambans plugin.

**Comment by Scags** [comment]
I think I know why people can rejoin the game and be able to join guards again. But I'm not sure why players can spawn at guard locations. Are the banned players spawning on blue team or are they spawning on red team?

**Comment by q1085909155** [comment]
He was born on the blue team

**Comment by q1085909155** [comment]
But he's not on the blue team

**Comment by Scags** [comment]
I think I see the problem. The plugin is changing the player's team when it is supposed to, but it doesn't send them to the right location. I'll see what I can do.

**Comment by q1085909155** [comment]
I may also have a question, why did the search plugin you provided not work

**Comment by Scags** [comment]
It might only be compatible with version 1.4 and under. V2.0 broke a lot of things.

**Comment by q1085909155** [comment]
I also have a map question. How do I close the voting map menu that pops up near the end of the map

**Comment by Scags** [comment]
Not sure. That has to do with whatever mapchooser plugin you're using.

**Comment by q1085909155** [comment]
I think I may know why the ban on a player disappears after he exits the game. Do I need to set the database? If so, how should I set it?
![捕获](https://user-images.githubusercontent.com/69096633/89510583-56252d80-d803-11ea-8cd1-19d866913f51.PNG)

**Comment by JohnyP41** [comment]
> 
> 
> I also have a map question. How do I close the voting map menu that pops up near the end of the map

press 0
