### ISSUE TITLE
Mechanized Mercenaries Music 

### ISSUE THREAD

**Issue by mrnoahfink** [Scags/TF2-Jailbreak-Redux#122]
Hello,

 when Mechanized Mercenaries LR over but Music keeps play next round.

here video to watch
https://drive.google.com/file/d/1zLcpXQIpzFwFzbG29f1wfntJbgrq-JT9/view?usp=sharing

**Comment by Scags** [comment]
Looks like its playing the theme every 0.1 seconds. What does your LR config file look like under Mechanized Mercenaries?

**Comment by mrnoahfink** [comment]
I am using YOUR Mechanized Mercenaries. and unfortunately there no LR config for it. 

https://github.com/Scags/TF2-LRModule-MechMercs

**Comment by Scags** [comment]
It should export to the config when it loads for the first time.

**Comment by mrnoahfink** [comment]
![jail](https://user-images.githubusercontent.com/66857858/89235792-81fea400-d5b4-11ea-998a-70e8322e83c7.png)

**Comment by Scags** [comment]
Looks like "time" exported incorrectly, change that to 130. I'll make a last-resort assertion to prevent bugs like that too. That might've happened while you were having trouble with themes in another issue.

**Comment by mrnoahfink** [comment]
Fixed
