### ISSUE TITLE
What is my problem

### ISSUE THREAD

**Issue by q1085909155** [Scags/TF2-Jailbreak-Redux#123]
How can I solve it
![图片1](https://user-images.githubusercontent.com/69096633/89864614-d1f5f000-dbde-11ea-9ca5-4a2d167da1be.png)
![图片2](https://user-images.githubusercontent.com/69096633/89864622-d4584a00-dbde-11ea-847d-76b6ea525d90.png)

**Comment by Scags** [comment]
Are you running a MySQL server or a MongoDB server? After some research it looks like the bans plugin is incompatible with MongoDB. I'll try to get around that and try to fix it so it works for both if I have the time.

**Comment by q1085909155** [comment]
I'm using SQLite

**Comment by JohnyP41** [comment]
You must use MySQL.
