### ISSUE TITLE
I found the problem

### ISSUE THREAD

**Issue by q1085909155** [Scags/TF2-Jailbreak-Redux#124]
Is lastRequests. CFG final request untranslatable? After I translated this file, I found that many requests failed to take effect and the VSH and PH disappeared from the list

**Comment by q1085909155** [comment]
> 是lastRequests。CFG最终要求不可翻译？翻译此文件后，我发现许多请求均未生效，并且VSH和PH从列表中消失了
I have done it correctly according to the translation method, and I only modified the behavior of Name in my native language

**Comment by Scags** [comment]
I think I mention in the wiki that translations are supported. That's a mistake, sorry. I didn't explain what I meant very well. If you want to change the language of a last request, you should simply be able to change "Name", "Description", "Queue_Announce", and "Activated" to whatever language you wish. 

For example (VSH):
```cs
	// You cannot change this, before the bracket, it will not work
	"Versus Saxton Hale"
	{
				// You can only change what is on the right side of the entries
				// If you change what is on the left (name, description, Queue_Announce, etc.) it will not work
		"name"		"Versus Saxton Hale"
		"description"		"Play a nice round of VSH"
		"Queue_Announce"		"{default}{NAME}{burlywood} has selected {default}Versus Saxton Hale{burlywood} as their last request."
	}
```

**Comment by q1085909155** [comment]
Yes, I changed the one on the right, but after I restarted the server, these requirements could not be shown, such as the requirement of Hot Prisoner. After the round started, Hot Prisoner appeared at the bottom of the screen, but the Prisoner was not lit

**Comment by Scags** [comment]
Strange, are there any errors in the logs?

**Comment by q1085909155** [comment]
Please wait for me for a moment, I think I need to try again

**Comment by q1085909155** [comment]
`SourceMod error session started
L 08/15/2020 - 15:40:32: Info (map "jb_minecraft_daylight_v8_fix") (file "/home/tf2server/serverfiles/tf/addons/sourcemod/logs/errors_20200815.log")
L 08/15/2020 - 15:40:32: [SM] Unable to load plugin "tf2jail-chatkills.smx": Could not find required plugin "tf2jail"
L 08/15/2020 - 15:40:32: [SM] Exception reported: Invalid Handle 180017c (error 3)
L 08/15/2020 - 15:40:32: [SM] Blaming: TF2Jail_Redux.smx
L 08/15/2020 - 15:40:32: [SM] Call stack trace:
L 08/15/2020 - 15:40:32: [SM]   [0] StringMap.GetValue
L 08/15/2020 - 15:40:32: [SM]   [1] Line 280, C:\Users\johnm\OneDrive\Documents\GitHub\TF2-Jailbreak-Redux\sourcemod\scripting/include\tf2jailredux/lastrequest.inc::LastRequest.GetKv
L 08/15/2020 - 15:40:32: [SM]   [2] Line 448, TF2JailRedux/natives.sp::Native_LastRequest_CreateFromConfig
L 08/15/2020 - 15:40:32: [SM]   [4] LastRequest.CreateFromConfig
L 08/15/2020 - 15:40:32: [SM]   [5] Line 8, BaseLRs/freedays.sp::Freedays_Init
L 08/15/2020 - 15:40:32: [SM]   [6] Line 47, C:\Users\johnm\OneDrive\Documents\GitHub\TF2-Jailbreak-Redux\sourcemod\scripting\TF2JR_BaseLRs.sp::OnLibraryAdded
L 08/15/2020 - 15:40:32: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName`

**Comment by q1085909155** [comment]
This is my error report during this period. I tried again, and all the final requirements I translated could not be used properly

**Comment by q1085909155** [comment]
![图片1](https://user-images.githubusercontent.com/69096633/90308220-51056400-df10-11ea-8e03-686f96f6e03b.png)
Maybe it will make it easier for you to understand

**Comment by Scags** [comment]
I think I see what's wrong. When an LR is created from the config, it deletes the current one if it already exists within the game, then recreates it. However, it deletes it by its name. Since you're changing the name, it's looking for whatever you named it, and can't find anything. Then, when it recreates itself, it finds the LR that it could not delete properly, and reattaches itself to the broken LR, causing that error.

It's kind of hard to explain but it should be a simple fix. However that should only happen if you are late-loading the "BaseLRs" plugin.

Give me a few minutes and I can fix it real quick.

**Comment by Scags** [comment]
Pushed. You can also try out the updated Teambans plugin and see if that is working properly. I reverted it to an earlier build and fixed the issue where banned red players would spawn at blue spawn.

**Comment by q1085909155** [comment]
The problem on LR has been fixed, but the issue of fixed where red players would spawn at blue spawn has not been good

**Comment by Scags** [comment]
Strange, I'll take a closer look when I get the chance.

**Comment by q1085909155** [comment]
Can it be compatible with the search plugin in the next update

**Comment by q1085909155** [comment]
Will the search plugin be compatible with the next update

**Comment by Scags** [comment]
I don't know. I did not write that plugin.
