### ISSUE TITLE
LR Config Problem

### ISSUE THREAD

**Issue by MrPanica** [Scags/TF2-Jailbreak-Redux#126]
Hey.

How to make "Random" Last Request to be the first on the Last Request menu?
I put this section first in the Last Request config, but it didn't give any result (

**Comment by Scags** [comment]
Looks like you may have to recompile the BaseLRs plugin. That's unintentional. The plugin creates the LRs before the config file is parsed. But for now you can re-order the functions below in any sequence you want to (in BaseLRs.sp).

```cs
public void OnLibraryAdded(const char[] name)
{
	if (!strcmp(name, "TF2Jail_Redux", true))
	{
		Random_Init();
		Suicide_Init();
		Freedays_Init();
		Custom_Init();
		Melee_Init();
		HHH_Init();
		Tiny_Init();
		Hot_Init();
		Gravity_Init();
		SWA_Init();
		Warday_Init();
	}
}
```
