### ISSUE TITLE
the plugin simply not working.

### ISSUE THREAD

**Issue by steedo1738** [Scags/TF2-Jailbreak-Redux#127]
I've tried all that I can to get this plugin to work, the old jailbreak plugin on allied modders works fine, but its missing some key elements and is just plain old. Id like to use this one really bad, but nothing I do works. Ive tried all the installation methods, and I am enabling the mod with the proper convars. If you have any idea how to help me that would be great.

**Comment by Scags** [comment]
Are you getting any errors in your error logs? My guess is that you're missing a plugin or extension that is needed. Which could either be TF2Items or TF2Attributes. 

The plugin should at the least accomplish something. Anything else must mean that it's failing to load. And it won't fail without giving a reason somewhere.

I'd say check your error logs and run `sm plugins list` in console and record any and all Jail Redux failures.

**Comment by steedo1738** [comment]
I was an idiot and accidently installed the wrong version of SM
