### ISSUE TITLE
Jailbreak now interfering with basecommands

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#13]
Hi Scags, first, thanks for the update! Btw any idea why the plugin is now interfering with basecommands? From what I know this is a default sourcemod plugin. Im going to try looking into the map config, but don't see why it's interfering with a default plugin to begin with, and wanted to make sure. Noticed it still interferes with other plugins, but same symptoms, no errors and plugins work in the beginning then randomly stop working as if there was a leak or something like that.
```
L 07/21/2018 - 08:04:11: [SM] Fatal error encountered parsing translation file "plugin.basecommands.txt"
L 07/21/2018 - 08:04:11: [SM] Error (line 0, column 0): Stream failed to open
L 07/21/2018 - 08:04:17: [TF2Jail_Redux.smx] ~~~~~No TF2Jail Map Config set, dismantling teleportation~~~~~
L 07/21/2018 - 09:01:46: Error log file session closed.
```
Oh btw if it helps it seems to fill up my logs so the error is occuring a lot.

**Comment by Scags** [comment]
Looks like you need to update SourceMod. Are you sure your map configs are under tf-/addons/sourcemod/configs/tf2jail ?

**Comment by unusual917** [comment]
Yea, that's the right directory. I'll go ahead and update sourcemod and see if that fixes it! Thanks!

**Comment by unusual917** [comment]
hmm after update I get this error
```
L 07/22/2018 - 19:59:13: [SM] Blaming: TF2Jail_Redux.smx
L 07/22/2018 - 19:59:13: [SM] Call stack trace:
L 07/22/2018 - 19:59:13: [SM]   [0] StringMap.GetValue
L 07/22/2018 - 19:59:13: [SM]   [1] Line 86, TF2JailRedux/jailbase.sp::JailFighter.bIsWarden.get
L 07/22/2018 - 19:59:13: [SM]   [2] Line 860, TF2JailRedux/jailhandler.sp::ManageClientDisconnect
L 07/22/2018 - 19:59:13: [SM]   [3] Line 631, C:\smbackup\sourcemod\scripting\TF2Jail_Redux.sp::OnClientDisconnect
```

**Comment by Scags** [comment]
I've been having that error for a while and I'm not sure how to fix it. I'll be looking into it more in depth later today
