### ISSUE TITLE
How to enable VSH and PropHunt? [Sloved]

### ISSUE THREAD

**Issue by TricksterRL** [Scags/TF2-Jailbreak-Redux#134]
I was making a Jailbreak server for my friend but its a local server not yet set to public because I'm using MyRepblic and I need static IP. I found out that the VSH and Prop Hunt is not inside of the last request how do I enable it?

Materials, Model and Sound has already put inside the folder.

There something I need to do?

**Comment by q1085909155** [comment]
I think you can look at the basics to see if they are perfect: 
1. Install plugins correctly 
2. Configured lastrequests. CFG

**Comment by TricksterRL** [comment]
I forgot to add one more plugin and also is there anyway to set timer like every 45 second rtd will activate on every single player who is alive

**Comment by q1085909155** [comment]
I don't know much about it. I hope Wikipedia can help you

**Comment by TricksterRL** [comment]
hmm
The WikiPedia didn't show anything related to repeating command every 45 second :/

**Comment by TricksterRL** [comment]
Nvm
Found what I'm looking for End_Cmd
