### ISSUE TITLE
Any way to remove certain LR's?

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#14]
The sniper LR is confusing to most of my players and hate it (just my players, not saying its bad for everyone; just my players). I'm sure some may like it, but for us, it would help to disable this LR. Any way we can disable this?

**Comment by Scags** [comment]
Well the plugin is essentially developer framework, so if you want to edit/remove lrs you'd have to edit jailhandler.sp
I took the time to edit it [here](https://www.dropbox.com/s/e8dw32pwhzxqfyu/jailhandler.sp?dl=0)
You'd have to drag it to tf/addons/sourcemod/scripting/TF2JailRedux/ and then drag TF2Jail_Redux.sp over spcomp.exe

**Comment by unusual917** [comment]
ah this is great since i only have to edit jailhandler if its updated, and not for every update you push. Thanks!
