### ISSUE TITLE
Warden menu instruction error!

### ISSUE THREAD

**Issue by q1085909155** [Scags/TF2-Jailbreak-Redux#155]
Hello, you the latest update in prison long menu unusable.The thing is, I downloaded your new file, installed it on my server and debugged it for use. When I opened the cell door using the warden's menu, no prompt popped up. When I opened the console, I found these outputs. Hope you can repair as soon as possible! Oh, and it's worth mentioning that the sentinel on the map has been retained, whereas previous plugins removed it.I think it's very good  @Scags 
![QQ截图20210717174406](https://user-images.githubusercontent.com/69096633/126033151-72967ca7-f582-4358-be2e-59e0a80fd87e.png)

**Comment by Scags** [comment]
Sorry about that. Someone was having an issue with it and I thought that it had to do with capitalized letters. That ended up removing "_" by accident. It's reverted now so please download the latest.
