### ISSUE TITLE
Can someone help me

### ISSUE THREAD

**Issue by q1085909155** [Scags/TF2-Jailbreak-Redux#158]
Is there a function of turn time? I want to do something after the turn time reaches the specified number.
For example,
if(g_Time == 5)
{
PrintToChatAll("Five minutes left. Red team allowed into the armory!" )
}

**Comment by MrPanica** [comment]
```
if(JBGameMode_GetProp("iTimeLeft")  ==  300)
{
    PrintToChatAll("5 minutes before the end of the round. Red team allowed into the armory!" )
}
```
or
```
if(gamemode.iTimeLeft == 300)
{
    PrintToChatAll("5 minutes before the end of the round. Red team allowed into the armory!" )
}
```

I think this should work.

**Comment by q1085909155** [comment]
JBGameMode_GetProp("iTimeLeft") works, thank you

**Comment by q1085909155** [comment]
Oh, hey, I was also wondering how I could add a Last Request judgment to the plug-in I wrote.
For example: if the turn is Last Request, the plugin will not run

**Comment by MrPanica** [comment]
> Oh, hey, I was also wondering how I could add a Last Request judgment to the plug-in I wrote. For example: if the turn is Last Request, the plugin will not run

It seems to me that it is better to start a New issue, where you could describe the problem in more detail and provide all the necessary data.

**Comment by q1085909155** [comment]
please #162
