### ISSUE TITLE
Few errors

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#16]
```
 08/11/2018 - 05:13:42: [SM] Exception reported: Invalid Handle 0 (error 4)
L 08/11/2018 - 05:13:42: [SM] Blaming: TF2Jail_Redux.smx
L 08/11/2018 - 05:13:42: [SM] Call stack trace:
L 08/11/2018 - 05:13:42: [SM]   [0] StringMap.GetValue
L 08/11/2018 - 05:13:42: [SM]   [1] Line 88, TF2JailRedux/jailbase.sp::JailFighter.bIsWarden.get
L 08/11/2018 - 05:13:42: [SM]   [2] Line 840, TF2JailRedux/jailhandler.sp::ManageClientDisconnect
L 08/11/2018 - 05:13:42: [SM]   [3] Line 634, D:\OneDrive\Sourcemod compiler\2018\TF2Jail_Redux.sp::OnClientDisconnect
```
Any idea on how this can get fixed?

**Comment by Scags** [comment]
This one I genuinely have no idea what's causing it. Not sure what I can do

**Comment by Scags** [comment]
Reopening this because there may be more errors just yet. Still dunno why it's erroring out.

**Comment by unusual917** [comment]
Alright Scags. Hope the bug gets found! Thanks for the help!

**Comment by Scags** [comment]
I'm unable to recreate this anymore (Last time I had this error was the 7th of this month). Have you tried updating SM? Assuming you're still having an error like this.

**Comment by Scags** [comment]
Closing. Was most likely a fluke or some bug with SM. Consult [this](https://forums.alliedmods.net/showthread.php?t=310249) for future reference.

**Comment by Scags** [comment]
Officially patched with one of the latest updates. Players disconnecting before `OnClientPutInServer` (and thus, the creation of the StringMap) would cause the error. The StringMap is now created `OnClientConnected`, see [9caa7bb](https://github.com/Scags/TF2-Jailbreak-Redux/commit/9caa7bbcfeefe2f952409fdc1fa3bc5b949d4a03).
