### ISSUE TITLE
Sql Injections Fixed?

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#2]
Since this is a fork from the original jailbreak plugin, I was wondering if it fixed the recently discovered sql injection vulnerabilities that was found. According to the github, the author pushed some commits recently that fixed a lot of them.  
https://github.com/ShadersAllen/TF2-Jailbreak/commits/Stable  
Are they implemented or necessary in this version?

**Comment by Scags** [comment]
Hi there.
Firstly this isn't exactly a fork, it's more of a rewrite of the entire plugin. Secondly, I've yet to actually make a working teambans plugin because I'm far too lazy. But I'm fairly certain that using [the original one](https://github.com/ShadersAllen/TF2-Jailbreak/blob/Stable/plugins/TF2Jail_TeamBans.smx) will work just fine with this plugin if needed.

**Comment by unusual917** [comment]
Sorry what are the latest binaries for again?

**Comment by Scags** [comment]
It's just the latest update to the plugin. I've yet to actually complete a teambans plugin explicitly for this plugin.

**Comment by unusual917** [comment]
Teambans isn't all that necessary since we can use mute to ban people from blue team. At least in my opinion.
  
Any chance you guys can implement these "directional hud text icons, if you will" as shown in this screenshot? This is from a server that runs a custom version of jailbreak, and this hud text implementation is amazing.
  
They use it to label wardens (attaches the message above their heads) and repeats (attaches message above prisoner's head for repeat). They also have it for "go here" functionality rather than the ones you guys use with this plugin. It's more effective since it guides the player better with a overlay on player screen showing which direction to look.
  
![untitled](https://user-images.githubusercontent.com/24946482/41216514-7e31f298-6d09-11e8-826b-c1f3cfd6ddff.png)


I opened up a new issue for feature request.
