### ISSUE TITLE
Bugs Problem with LR's

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#21]
Hi Scags,
For some reason, these bugs occur for LR's making it unusable for now, at least for my install.
1) Warday: causes red players to spawn without weapons, T-pose. Supposedly this had issues on my previous version but noone reported it.
2) Classwars: causes red players to spawn without weapons, T-pose.
3) HHH: HHH model doesn't equip. This one worked fine in my previous install.
4) Saxton Hale: teamswitches a player instantly killing the player
5) PH: Isn't showing up on LR menu, I used !flr The last option isn't labeled PH in menu and it is blank. I tried choosing it but it didn't do anything.

I remember old wiki said we had to change a config for saxton and PH to work, but I don't see it anymore. Also, I used your compiled plugins and updated the /cfg/sourcemod config too.

I opened up another issue with warden menu in different post on git tracker.

**Comment by Scags** [comment]
I PROBABLY should've tested before throwing out an update. Lol, reverted with latest commit.

**Comment by Scags** [comment]
I'm 99.9% I fixed the broken stuff. Now to fix the other broken stuff.

**Comment by unusual917** [comment]
Hey Scags, thanks for the response. What other broken stuff are you referring to btw? Also saxton and PH doesn't require a config change anymore right? I haven't used it before but I remember a config I had to change for removing or adding those LR's.

**Comment by Scags** [comment]
I was being facetious. But there are probably still things I need to fix. 
The config editing was removed in a previous update. Now you can simply add and remove the plugins at will and the core plugin handles everything else.
