### ISSUE TITLE
Request: Annotations

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#3]
Here is a thread describing how to attach annotation to player heads https://forums.alliedmods.net/showthread.php?p=1971738
Here is a plugin that allows players to annotate stuff on the map https://forums.alliedmods.net/showthread.php?p=1317304

As shown as image below, I was wondering if you could implement annotations where users can type commands to:
1) Ask for a repeat with !repeat (and !r) and gets the annotation attached to his head that says "{player_name} asked for a repeat." There should be a configurable amount of times each client can use this per round, as it can be abused if not.
2) Automatically attach "warden" annotation to warden's head in beginning of round for a configurable amount of seconds.
3) Replace marker functionality currently implemented with Scag's version with these annotations as they are made to direct players to the message point. Same functionality, aim at area and use command to place the marker, but in this case an annotation that says "here." Configurable for amount of time the message stays alive.

![image](https://user-images.githubusercontent.com/24946482/41216671-1f24dc4c-6d0a-11e8-9f9e-df81832a7f19.png)

**Comment by Scags** [comment]
Looks great, I'll make the warden and marker ones enableable by cvar. For repeat I'll just make a separate plugin. Thanks for the links btw

**Comment by unusual917** [comment]
Thank you Scags, my pleasure!
