### ISSUE TITLE
[Idea] Auto Updates

### ISSUE THREAD

**Issue by Karmatik** [Scags/TF2-Jailbreak-Redux#30]
Hi, I know how to add an auto-updater system, and I can host it you for free, I'm just saying this because not everyone knows this keeps updating and somebodys loses the opportunnity of use this amazing plugin

**Comment by Karmatik** [comment]
If you want, I'll add the code for u

**Comment by Scags** [comment]
Although I appreciate the offer, I'm not sure if I want updater support for it. I kinda expressed this in the readme, the plugin is developer framework, so it's meant to be changed and updated by the user (who can always upstream updates from the main repo). So they'll probably remove the updater section anyways. Although I could just add a macro for compiler inclusion. Secondly, if I did add updater support, I'd prefer to host it myself. Once again thanks for the offer.
