### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MrPanica** [Scags/TF2-Jailbreak-Redux#39]
If I run the command on several players at the same time, then the server goes into crash.
For example: sm_slap @all, even when there are 8 people on the server, it also works on bots.
This is valid only for the version of the plugin 1.1.0, in the previous version everything was fine, I checked.

I consistently deleted all the plugins and concluded that crash happens because of your plugin.

For clarity, I recorded a video about it.
When I enter "sm plugins reload TF2Jail_Redux.smx" I change the version of Jail Redux to 1.1.0.
https://youtu.be/1VO8H--tNIw

I also have an Accelerator
Here is a link to it: https://crash.limetech.org/ncbwiglwm6bc

**Comment by Scags** [comment]
I can’t reproduce this, so I’m not sure what to tell you. If it’s happening consistently or every time you use a command then I would try updating SourceMod.

**Comment by MrPanica** [comment]
Thanks for the answer! SM updated - did not help, I will wait for the next version of the plugin, maybe it will fix the error. In the meantime, I will use the old version of your plugin)

**Comment by Scags** [comment]
Already I managed to recreate it. Am now in the process of fixing it.

**Comment by Scags** [comment]
Scratch that, that was something to do with role renderer particles. Sorry lol.

**Comment by MrPanica** [comment]
Found a problem.
After updating TF2Items errors were gone.

**Comment by Scags** [comment]
Good to hear!

**Comment by MrPanica** [comment]
Problem still exists,
now it works less frequently. When there are no players on the server, but there are bots, it does not work at all. You said you were able to repeat my mistake, can you continue to correct it?

**Comment by Scags** [comment]
I thought I replicated it, but that was something completely different. Are you still having this problem?

**Comment by MrPanica** [comment]
Yes, the problem remains. My server is hosted on a private game hosting, maybe the problem is this? But there is 4 GB of RAM, and the value of the processor never rises above 80%

**Comment by MrPanica** [comment]
Maybe you made some dramatic changes? I want to remind that version 1.0.1 works for me, and others crash my server.

**Comment by MrPanica** [comment]
It seems that the problem is only on my server, now there are no failures on my server. Although it is strange, but it is a fact. The latest build server is stable. Who knows, maybe there will be a crash again.
