### ISSUE TITLE
This one not needed, delete please

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#4]
Nvm, not needed.

**Comment by Scags** [comment]
I get what you mean by this, but the way I have the plugin set up with warden commands is a little bit different than the original TF2Jail's. I'm putting "Low Priority" for now but I'll keep it in mind.

**Comment by unusual917** [comment]
Hi Scags, just to elaborate, so it's already implemented in the warden commands?

**Comment by Scags** [comment]
Not necessarily, there's already a cvar to dictate what flag is required for VIP perks (which I think is "a"), but there isn't anything explicit for warden commands. But something like this I'll keep in mind

**Comment by unusual917** [comment]
ah ok, thank you.

**Comment by unusual917** [comment]
I also added a second feature on original post that would go well with this functionality.
