### ISSUE TITLE
Issue with chat messages

### ISSUE THREAD

**Issue by YoinksX2** [Scags/TF2-Jailbreak-Redux#41]
Most messages(mostly relating to the warden menu) sent due to the jb plugin are spammed 3 times in chat rather than just once. I'm not sure what causes this and I would like to request a quick fix.

**Comment by Scags** [comment]
Not sure what's wrong. You could try updating SourceMod and/or compile the plugin from your end.

**Comment by BenediktKa** [comment]
This is probably an issue on your end.
Do you have multiple versions of the plugin installed?
Did you try restarting your server?

**Comment by Scags** [comment]
I'm going to assume that this is taken care of and close.

**Comment by uniacke1** [comment]
Sorry, re-opening. We still have the issue with no plugins other than JB/basecomms loaded.

Interesting find though, we did at one point manage to make it go up to 5 repeats after unloading a bunch of plugins to try to debug. Some messages happen once as expected, others twice. It went back to 3 on mapchange.

 I suspect it may be related to plugin hook attachments not getting cleaned up (during reload/refresh?) and the same event triggering the code multiple times.

**Comment by BenediktKa** [comment]
Reloading might indeed break some stuff however map changes should run smoothly. Do you have any issues with map changes?

**Comment by uniacke1** [comment]
not to my knowledge

**Comment by BenediktKa** [comment]
Do you have any use for reloading plugins? Since otherwise it would seem like a very minor issue

**Comment by YoinksX2** [comment]
While testing we did not receive any errors. Our only lead is the suspicion mentioned earlier regarding plugin good attachments.

**Comment by Scags** [comment]
I once had an issue like this a few years ago when I compiled a plugin from my VPS. Are you doing this and if not, have you tried compiling the plugin yourself?

**Comment by uniacke1** [comment]
yes, we are self compiling because we disable the sniper LR. No direct correlation, 3 messages when 1 person in the server, we added bots and it does not change the number. We got five in this scenario once but were unable to reproduce how we got it to print more.

**Comment by Scags** [comment]
Ok **fortunately** in the next update I’m removing sniper and replacing it with something more enjoyable. This will probably fix this issue so I’ll see if I can get round to it this weekend. It’s finished i just need to test.

**Comment by uniacke1** [comment]
Forgot the other reason we self-compile is sourcebans does not work for us in the pre-compiled SMX. So while it would fix the chat issue... it would not address that particular one. :(

**Comment by uniacke1** [comment]
Any chance you could provide a zip of your "scripting" folder which you are using to compile your plugin? That way I can run a diff and maybe see what is causing either the text or SB issues.

**Comment by Scags** [comment]
If you're using SB++ then that's understandable. I didn't have that include in my scripting folder. I have it now so that'll be included in the next update.

**Comment by uniacke1** [comment]
Plain old sourcebans, unfortunately. (Was originally filed as #38)

**Comment by uniacke1** [comment]
Looks like your addition of the SB++ inc fixed #38 for whatever reason. So with the removal of Sniper we no longer need to self-compile and are rid of the chat-spam as well.
Thanks

**Comment by Scags** [comment]
Wonderful!
