### ISSUE TITLE
Teambans issue

### ISSUE THREAD

**Issue by YoinksX2** [Scags/TF2-Jailbreak-Redux#43]
Teambans are busted for us.

Quick rundown of what it does:
-Allows you to teamban a player
-The teamban slays the player and puts them on red
-However the player can rejoin blue the next round

It looks like it does all the right things in the rcon but we cannot figure out why the ban doesn't stick around.

**Comment by Scags** [comment]
Are they spawning after the round starts? Because that is a feature you can control via cvar `sm_jbans_ignore_midround`. Set that to 0 if you need. If it isn't then I'm not sure what's up but I'll be sure to double check that later today. Do you have any errors in your logs?

**Comment by YoinksX2** [comment]
Any progress?

**Comment by Scags** [comment]
I've got it ready I just need to test. It's finals week currently so I'm limited on time for a few days.

**Comment by YoinksX2** [comment]
Hows finals, e-money?

**Comment by Scags** [comment]
I probably passed.
I've update the plugin *finally* but I'm gonna keep this open so you can let me know if it worked on your side.

**Comment by YoinksX2** [comment]
Seems like everything is working fine.
