### ISSUE TITLE
A few shortcomings

### ISSUE THREAD

**Issue by MrPanica** [Scags/TF2-Jailbreak-Redux#44]
Thanks for the new version!
I found a few flaws in this version.

1. There is an incorrect bracket in the translation file.

```
"Prisoner Has Rebelled"
{
"#format" "{1: N}"
"en" "{default {{1} {burlywood} has rebelled."
}
```

2. The variable sm_tf2jr_rebel_timer indicates an incorrect maximum value.

`cvarTF2Jail [RebelTime] = CreateConVar ("sm_tf2jr_rebel_timer", "30", "Timer for the Rebel system, if it's enabled.", FCVAR_NOTIFY, true, 0.0, true, 1.0);`

3. If a player is issued a freeday, but he enters the blue team, then he remains a particle of freeday.

**Comment by Scags** [comment]
Ok thanks for letting me know. I’ll be sure to take care of this before the end of the day.
