### ISSUE TITLE
TF idle kicked at round start

### ISSUE THREAD

**Issue by Krazyclass** [Scags/TF2-Jailbreak-Redux#49]
Hey, now I have a different problem. I had this same problem with the old TF2Jail plugin so I have a feeling it's a server error but was wondering if you could help as you have experience. Here is the story:

After installing your plugin which works absolutely fine, I got some friends to join my rented server running the map ba_mlcastle_v10. I joined red and a friend joined blue. When the countdown to start the round ended and the round started it kicked people for inactivity automatically. I have set sv_timeout 2000000000, mp_idlemaxtime 200000000000 and mp_idledealmethod 1. As I had this issue with the old plugin I don't think it's a problem with your plugin. But would appreciate the help anyway.

![image](https://user-images.githubusercontent.com/44714699/47947220-53035c00-df10-11e8-8c10-0d03c02c29f8.png)

**Comment by Scags** [comment]
You could try mp_autokick 0 but I'm not sure if that'll fix it.  It's most likely a cvar that the plugin changes but idk which one.

**Comment by Krazyclass** [comment]
I have no idea, in TF2 the idle commands are the 3 I stated above. mp_autokick isn't a command that is recognisable in TF2 or the server console. I've looked through the cvars but I don't see any that should conflict with idle management.

**Comment by Krazyclass** [comment]
Ok just did a test, the map/server runs fine without the plugin with no sudden tf idle kicks. So TF2jailbreak plugins must have something against my server. XD

**Comment by Krazyclass** [comment]
Still got the problem, will try each cvar out later and find out if one is causing this issue. I'll let you know if I get any results.

**Comment by BenediktKa** [comment]
Please try setting these cvars:
mp_idlemaxtime 0
mp_idledealmethod 0

**Comment by Krazyclass** [comment]
Thank you Benefikt, I did as you said and it now works. I thought that having a high number would mean that it would be fixed turns out I was wrong and you was right. Much appreciated.
