### ISSUE TITLE
Request: VIP Upgrades

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#5]
1) Since this version already has vip setup, can we have it so vip players have priority for warden? So vip players in blu can override wardens by typing !w during the beginning of round cooldown? But they won't be able to if the warden is already vip?

2) Also, i thought it would be nice to have a config where players can play warden for so many rounds _in a row._

3) How about different levels for VIP flags? Like flag "a" is higher than flag "q." I thought this would be nice for admins to have special priority over VIP's.

**Comment by Scags** [comment]
The only perks that admins/VIPs have at the moment is bypassing plugin muting, so more perks for them is probably a bit more desirable. 

1. Can be done, but couldn't VIPs strictly hog warden? Especially if there are multiple on Blu team.
2. Agreed, To-do
3. There's already a cvar for admin flags, "sm_tf2jr_admin_flag" but like I said before, the only perks at the moment have to do with plugin muting (which needs to be reworked)

**Comment by unusual917** [comment]
Thanks for the response Scags!
As for admin flag perk, didn't know that! For this "admin flag" VIP, can we call it premium VIP? Since in my opinion, I think it would be nice to have some non-admins have premium vip.

**Comment by Scags** [comment]
You can just change the flag to include them, but in return they'll never be muted via plugin.

**Comment by Scags** [comment]
As of right now jf other plugins are doing muting then it’s possible that player could get stuck in a mute loop where they either will never be unmuted or muted. 
Well as I’ve just figured out, if you’re running sourcebans/sourcecomms then muting is probably fucked up. So I really really need to fix plugin muting

**Comment by unusual917** [comment]
Yea, I use sourcebans++ with its sourcecomms. When you mute red, it's not done through sourcemod's sm_mute is it? I think the way you have it by default is fine, if it just simply mutes red team without tinkering with sourcemod's sm_mtue, and for individual mutes, admins can handle those.

**Comment by Scags** [comment]
So the plugin, whenever it does muting, checks to see if the client is “for real” muted (sm_mute, sm_silence). And depending on which plugin the server is running (basecomms or sourcecomms) it checks if that plugin has that client muted. If they’re muted then the plugin ignores having to mute the client. For some reason with the server I’m working with currently, that’s been an issue and they’re running sourcecomms. On my own test server I’m running basecomms and that’s fine. So I’m kinda confused on what the issue is. According to you it sounds like it’s working fine, confusing me even more :/

**Comment by unusual917** [comment]
Well, maybe I overlooked the time when red was unmuted, and it did actually unmute them. Can't say for sure since I haven't completely released the jailbreak server yet (waiting for the updates that I requested) and I have no one to test it with at the moment. I'll try to get that double checked when I get people on next time.

**Comment by Scags** [comment]
I guess I’ll comment here. Sorry for putting off all of the stuff you’ve been wanting. I’d say that I’ve been busy but that would be a half-lie. I’ve been more or less lazy when it came to the jailbreak plugin and I’ll be out of commission for the next 2 weeks. But after that I *promise* to finish up everything you’ve requested prominently.
