### ISSUE TITLE
Particle Installation

### ISSUE THREAD

**Issue by MrPanica** [Scags/TF2-Jailbreak-Redux#52]
I found a good effect that I would like to put on my head, but it appears under my feet, how can I fix it?
https://streamable.com/i8m7

**Comment by Scags** [comment]
Technically a client's 'origin' is at their feet, so the particle would go their naturally. This gives me an idea, so I'll make an issue to remind myself to add something to help with this. I'm thinking either attachment points or offsets, or both.
In the meantime you're just stuck with it at your feet 😛.

**Comment by Scags** [comment]
Got that with latest update, should work but if anything is wrong let me know.
