### ISSUE TITLE
Jailbreak Map Configs HERE!

### ISSUE THREAD

**Issue by Salamon75** [Scags/TF2-Jailbreak-Redux#53]
This is not an issue but we spent so many hours to make some JB map compatible. So this is a little help for those using these maps. Here is our config which would work with these maps. Meaning opening cells etc.
"TF2Jail_MapConfig"
{
	"ba_hopjb_v8"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"21.31"
				"Coordinate_Y"		"568.75"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-1515.90"
				"Coordinate_Y"		"-115.88"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-6451.30"
				"Coordinate_Y"		"-315.06"
				"Coordinate_Z"		"75.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_famouz_2_final"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"*113"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"152.61"
				"Coordinate_Y"		"0.90"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"822.28"
				"Coordinate_Y"		"628.89"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"3664.74"
				"Coordinate_Y"		"1.51"
				"Coordinate_Z"		"75.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"ba_jailfort_b1"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"286.94"
				"Coordinate_Y"		"131.91"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-203.00"
				"Coordinate_Y"		"455.96"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-658.24"
				"Coordinate_Y"		"3535.65"
				"Coordinate_Z"		"43.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"ba_jail_casuarina_b5"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cd"
		"CellsButton"		"*301"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-4312.05"
				"Coordinate_Y"		"2687.87"
				"Coordinate_Z"		"-436.97"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-2740.90"
				"Coordinate_Y"		"3446.72"
				"Coordinate_Z"		"-436.97"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-1013.76"
				"Coordinate_Y"		"10980.97"
				"Coordinate_Z"		"-421.47"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"ba_space_jail_v7"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-574.74"
				"Coordinate_Y"		"-1215.88"
				"Coordinate_Z"		"411.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"238.53"
				"Coordinate_Y"		"-429.49"
				"Coordinate_Z"		"203.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"2043.39"
				"Coordinate_Y"		"5035.82"
				"Coordinate_Z"		"-158.33"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"ba_mlcastle_v10"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"466.96"
				"Coordinate_Y"		"-945.52"
				"Coordinate_Z"		"107.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-306.64"
				"Coordinate_Y"		"-1183.70"
				"Coordinate_Z"		"107.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"1207.30"
				"Coordinate_Y"		"3659.66"
				"Coordinate_Z"		"187.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_fuckzz_final_v11"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"opencells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"531.06"
				"Coordinate_Y"		"569.36"
				"Coordinate_Z"		"69.53"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-465.76"
				"Coordinate_Y"		"27.54"
				"Coordinate_Z"		"69.53"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-3484.69"
				"Coordinate_Y"		"543.80"
				"Coordinate_Z"		"69.53"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_minecraft_night_final_v5"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"1323.91"
				"Coordinate_Y"		"480.09"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"1280.00"
				"Coordinate_Y"		"1344.00"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-3017.00"
				"Coordinate_Y"		"-2570.86"
				"Coordinate_Z"		"203.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_simple_b9"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"*74"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"123.92"
				"Coordinate_Y"		"-297.72"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-863.34"
				"Coordinate_Y"		"351.68"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-3135.10"
				"Coordinate_Y"		"2097.71"
				"Coordinate_Z"		"204.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_supermario_v13"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cells"
		"CellsButton"		"button_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-448.68"
				"Coordinate_Y"		"-964.42"
				"Coordinate_Z"		"459.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"192.00"
				"Coordinate_Y"		"-960.00"
				"Coordinate_Z"		"459.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-2809.81"
				"Coordinate_Y"		"2359.92"
				"Coordinate_Z"		"459.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_minecraft_daylight_v8_fix"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"1259.21"
				"Coordinate_Y"		"483.68"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"1172.88"
				"Coordinate_Y"		"1290.31"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-2512.42"
				"Coordinate_Y"		"-3331.16"
				"Coordinate_Z"		"139.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_complex_b6"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		// NEM TÖLTI BE AZ ENTSPY - A CELLNAME ÉS A CELLSBUTTON ISMERETLEN!!!
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"1053.16"
				"Coordinate_Y"		"-650.57"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"271.21"
				"Coordinate_Y"		"-706.66"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"226.14"
				"Coordinate_Y"		"4929.36"
				"Coordinate_Z"		"-308.97"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"ba_jail_wip_a6v4"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"Jaildoor"
		"CellsButton"		"cb"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-2451.82"
				"Coordinate_Y"		"829.93"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-3074.86"
				"Coordinate_Y"		"565.95"
				"Coordinate_Z"		"76.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"3556.93"
				"Coordinate_Y"		"-1670.70"
				"Coordinate_Z"		"81.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_quake_b5"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		// NEM TÖLTI BE AZ ENTSPY - A CELLNAME ÉS A CELLSBUTTON ISMERETLEN!!!
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"236.13"
				"Coordinate_Y"		"53.28"
				"Coordinate_Z"		"11.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-703.90"
				"Coordinate_Y"		"128.12"
				"Coordinate_Z"		"11.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-2218.30"
				"Coordinate_Y"		"2539.60"
				"Coordinate_Z"		"11.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"ba_chretien_v1c"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"268.59"
				"Coordinate_Y"		"3664.58"
				"Coordinate_Z"		"75.03"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"480.00"
				"Coordinate_Y"		"2928.00"
				"Coordinate_Z"		"571.03"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"5000.00"
				"Coordinate_Y"		"-269.83"
				"Coordinate_Z"		"75.03"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server

	"jb_ponyjail_a2_fix"
	{
		// Cell names can be found included with the map, if not these are the usually most common
		// A CELLNAME ÉS A CELLSBUTTON ISMERETLEN!!!
		
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-205.99"
				"Coordinate_Y"		"5022.15"
				"Coordinate_Z"		"-164.97"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"1282.74"
				"Coordinate_Y"		"5176.00"
				"Coordinate_Z"		"-164.97"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-4721.99"
				"Coordinate_Y"		"3175.12"
				"Coordinate_Z"		"-164.97"
			}
		}
	}
	// Obviously you would repeat the same tree for each map in your server
}

**Comment by MrPanica** [comment]
Here is a small addition.
```
"TF2Jail_MapConfig"
{
	"jb_famous_final"
	{
		"CellNames"			"cell_door_1"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"

		"Freeday"
		{
			"Teleport"
			{
				"Status"			"0"
				"Coordinate_X"		"-50.0"
				"Coordinate_Y"		"13.0"
				"Coordinate_Z"		"58.0"
			}
		}
	}
	"jb_gulag_rc_0_20_0"
	{
		"CellNames"			"prisondoor"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"

		"Freeday"
		{
			"Teleport"
			{
				"Status"			"0"
				"Coordinate_X"		"74.0"
				"Coordinate_Y"		"-963.0"
				"Coordinate_Z"		"208.0"
			}
		}
	}
	"jb_soviet"
	{
		"CellNames"			"jailcells"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"

		"Freeday"
		{
			"Teleport"
			{
				"Status"			"0"
				"Coordinate_X"		"0.0"
				"Coordinate_Y"		"0.0"
				"Coordinate_Z"		"0.0"
			}
		}
	}
}
```

**Comment by Scags** [comment]
Thanks both. This was added in the latest update.
