### ISSUE TITLE
Change to steamworks instead of steamtools

### ISSUE THREAD

**Issue by uniacke1** [Scags/TF2-Jailbreak-Redux#55]
Steamtools causes consolespam of 

"..\common\pipes.cpp (528) : Assertion Failed: m_OutstandingCallbackThreadId != ThreadGetCurrentId()  "

 using SteamWorks instead is recommended for SetGameDescription in jailevents.sp

https://forums.alliedmods.net/showthread.php?t=277960

**Comment by Scags** [comment]
That's probably the better one to use anyways. I'll do that for the next update.
