### ISSUE TITLE
weapon blocker

### ISSUE THREAD

**Issue by gladoncio** [Scags/TF2-Jailbreak-Redux#58]
Is it possible to make a version of weapons blocker with external teams for any server?
not depend on tf2jail.
please I would appreciate it.

**Comment by Scags** [comment]
You can try https://forums.alliedmods.net/showthread.php?p=2120214 but it isn’t maintained plus it uses gamedata.

**Comment by gladoncio** [comment]
yeah, but I would like a version of your plugin, since you can ban by team

**Comment by Scags** [comment]
There's probably something like this that exists somewhere. I just don't have the time to work with other plugins at the moment.
