### ISSUE TITLE
Changing the Prefix TF2Jail

### ISSUE THREAD

**Issue by ruymb** [Scags/TF2-Jailbreak-Redux#59]
Hi there i am trying to change the Prefix of TF2Jail i have been through every file and even found the one with Crimson and Orange Tags and after changing it nothing happened.

**Comment by MrPanica** [comment]
I think you should open the tf2jailredux.inc file and change the prefix there, then compile the plugin.
![image](https://user-images.githubusercontent.com/44004288/48949923-a7678d80-ef4a-11e8-991f-456a08db414a.png)

**Comment by ruymb** [comment]
Oh why do we have to recompile the plugin?

**Comment by MrPanica** [comment]
Well, so it is necessary, it is not a config.
