### ISSUE TITLE
Request: Warden toggle mute red team

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#6]
Can we add mute toggle ability for reds to warden menu and with a command also?

**Comment by Scags** [comment]
Can be done, although it'd most likely be a menu with specifics as to who needs to be muted/unmuted.
Pseudo-below

1. Mute All Reds
2. Mute all non-VIP Reds
3. Default muting
4. Unmute all Reds

Or something of the sort.

**Comment by unusual917** [comment]
Interesting idea.

The only concern with player list muting is that it can be abused easily. The reason I like the muting functionality that you have now is that it doesn't touch "sm_mute,gag,silence" and I don't have to worry about someone accidentally getting muted with an admin command.

**Comment by Scags** [comment]
Closing, I don't think it's wise to trust a warden with this much control over gameplay, even if it's cvar'd. However it can be done third-party, the structure is set up in the gamemode properties and natives. 
*Hint hint nudge nudge people reading this in the future.*
