### ISSUE TITLE
Repeat Option is not working

### ISSUE THREAD

**Issue by ruymb** [Scags/TF2-Jailbreak-Redux#60]
I've added the repeat plugin and for some reason it's not working at all.

[SM] Plugin TF2JailRedux_RepeatAnnotation.smx failed to load: Unable to load plugin (no debug string table).

**Comment by MrPanica** [comment]
I solved this by recompiling the plugin.

**Comment by MrPanica** [comment]
Yes, but I'm from Russia, so a language barrier problem may arise.
https://steamcommunity.com/id/7656119810999042/

**Comment by Scags** [comment]
Fixed in latest commit. Recompiled with SM 1.9
