### ISSUE TITLE
Error spamming on console

### ISSUE THREAD

**Issue by Karmatik** [Scags/TF2-Jailbreak-Redux#65]
Blaming: TF2Jail_Redux.smx
L 12/29/2018 - 04:22:20: [SM] Call stack trace:
L 12/29/2018 - 04:22:20: [SM]   [0] ThrowError
L 12/29/2018 - 04:22:20: [SM]   [1] Line 444, C:\_tf2\tf2\tf\addons\sourcemod\scripting\include\entity_prop_stocks.inc::SetEntityRenderColor
L 12/29/2018 - 04:22:20: [SM]   [2] Line 1499, C:\_tf2\tf2\tf\addons\sourcemod\scripting\TF2Jail_Redux.sp::HideCurrentParticles
L 12/29/2018 - 04:22:20: [SM]   [3] Line 844, C:\_tf2\tf2\tf\addons\sourcemod\scripting\TF2Jail_Redux.sp::Timer_PlayerThink

**Comment by Scags** [comment]
Was already notified about this but thanks for the reminder. I left my laptop charger at my dorm, so ya gotta sit tight for a bit 😅. In the meantime you could change the whatchamacallit cvar and not let anyone use cloak.
