### ISSUE TITLE
My Suggestions for update

### ISSUE THREAD

**Issue by RWolfyo** [Scags/TF2-Jailbreak-Redux#66]
1: Make a mute/unmute menu for warden to mute/unmute red players in round (That's a very usefull functionality that was in cs 1.6 jailbreaks all the time as i remember, also remember about sourcecomms++)

2: Fix the dammn render spam that makes renderroles.cfg not working and forced me to throw it out so it wont spam meh console ;-;

3: Bring back the Sniper LR! Meh players loved it! warden randomly dying mid round was fun :D (The new LR is cool too, but tbh it should have other teleport locations than warday cause some of the warday locations on maps are very hard for red -/- blue meet and fight)

**Comment by Scags** [comment]
1. Yea that was suggested a bit ago, has been on my list so I'll see what I can do.
2. I know lol. You can change "sm_tf2jr_hide_particles" to 0 to stop it for the time.
3. I'm SORRY but every server I've joined had people complaining about it, so I just threw it out. I don't know much about maps and their warday locations. I just wanted to make sure prisoners and guards had ample time to be situated. Keeping them in their regular spawns (on most maps) really through them into the fray right off the bat.

**Comment by RWolfyo** [comment]
1. <3
2. <3
3. It's okay I mean you're the saviour of this game mode in tf2 so lulz, no pressure, if the mass want's it then let it be *red army choir joins the game*.

**Comment by Scags** [comment]
Muting is now toggleable with the latest update 👍
