### ISSUE TITLE
SV_StartSound Wackiness

### ISSUE THREAD

**Issue by Scags** [Scags/TF2-Jailbreak-Redux#68]
This
![](http://i1076.photobucket.com/albums/w442/Ragenewb/this_zps4bcjuc1h.png)
Doesn't
![](http://i1076.photobucket.com/albums/w442/Ragenewb/doesnt_zpsopuahclo.png)
Look
![](http://i1076.photobucket.com/albums/w442/Ragenewb/look_zpsmanyw08e.png)
Right
![](https://i1076.photobucket.com/albums/w442/Ragenewb/right_zpscjvtl0i8.png)

?????

Happens when the round ends/starts and randomly midround.
What.

**Comment by Thordin** [comment]
Disabling the music convar gets rid of the vast majority of these messages.

https://github.com/Scags/TF2-Jailbreak-Redux/blob/d1e81e634710414c75c511b318a8b45231702d77/sourcemod/scripting/TF2Jail_Redux.sp#L838

I am guessing maybe you need to do sound[0] = 0 and not char sound[PLATFORM_MAX_PATH] = "". Or maybe ManageMusic(sound, time) is destroying the sound string somehow.

https://github.com/Scags/TF2-Jailbreak-Redux/blob/d1e81e634710414c75c511b318a8b45231702d77/sourcemod/scripting/TF2Jail_Redux.sp#L1397

You should probably also check if strBackgroundSong is valid here and make sure it is initialized with a null byte.

https://github.com/Scags/TF2-Jailbreak-Redux/blob/d1e81e634710414c75c511b318a8b45231702d77/sourcemod/scripting/TF2Jail_Redux.sp#L1426

**Comment by Scags** [comment]
Game. Set. Match.
