### ISSUE TITLE
Can't disable friendly fire ability for wardens

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#7]
Hi Scags,
1) Is there a way to disable friendly fire toggling for wardens? I noticed with admin overrides, wardens can toggle ff still with warden menu. I guess make warden menu configurable?

2) Would love to see a cvar where only Warden can kill friendlies to kill bad blu's. So basically Wardens can kill anyone while others have ff off.

**Comment by Scags** [comment]
1 can be a to-do, but until I redo warden commands I'll have to put it on hold
2 would be tricky, _really_ tricky at that and also abuseable if I could ever get it to work.

**Comment by unusual917** [comment]
Alright scags, thanks for the response!

**Comment by unusual917** [comment]
I found a plugin that may help with number 2.
https://forums.alliedmods.net/showthread.php?t=64905

I know it can be abused but would be nice to have a cvar like this for us to choose to use it or not. We have wardens that can really use something like this whenever guards decides to break the rules.

**Comment by Scags** [comment]
Closing because this can be disabled in the wardenmenu config.
