### ISSUE TITLE
New update issues

### ISSUE THREAD

**Issue by RWolfyo** [Scags/TF2-Jailbreak-Redux#70]
1. Warden muting is not working at all other side than the menu showing stuff, and seem like it changed but it didn't (I'm using sourcebans++ and sourcecoms++ idk if that got anything to it)
2. Guard invites seem not borking at all either, I invited a random player, he accepted it nothing really happen on the round either on next round
3. pls fix d(o.o)b
4. No errors showed up in console while using these features so :man_shrugging:
edit:
also the Warden invited text shows only to the player invited, not to everyone.

**Comment by Scags** [comment]
Son of a-

**Comment by MrPanica** [comment]
I have the same problems.

Scages, thanks for the displacement of particles, but I meant a little more.
Currently, if the particles are displaced so that they are on the head of the warden, and he sits, then the particles are displaced relative to the player’s camera.

Can you attach particles to a specific part of the model, for example, to the head?
I want to install this particles https://streamable.com/i8m7


![20190110014333_1](https://user-images.githubusercontent.com/44004288/50934357-76e79e80-1479-11e9-8889-8c87a6e9d58f.jpg)
![20190110014336_1](https://user-images.githubusercontent.com/44004288/50934358-77803500-1479-11e9-8eef-ac00a6a1542c.jpg)
![20190110014346_1](https://user-images.githubusercontent.com/44004288/50934359-77803500-1479-11e9-9c13-2d1531b23232.jpg)
![20190110014352_1](https://user-images.githubusercontent.com/44004288/50934360-77803500-1479-11e9-83ef-17cb76a31618.jpg)

**Comment by MrPanica** [comment]
Does not print hud-text with the last wish.
How could I not notice this before.

**Comment by Scags** [comment]
I didn't notice it either lmao. I know what's wrong though.

**Comment by RWolfyo** [comment]
New issue found by my players (Works on other servers that use tf2jail redux, checked myself to make sure it's not my issue only):
- Demoman can get ammo on round start by doing these as the round starts:
Be demoman, have any type of shield equipped at the time.
Before round starts quickly go to inventory, and swap that shield to any sticky launcher
Respawn by kill or change to any class and back to demo
Demo spawns with ammo to sticky launcher he equipped.
(i got banned from random czech server xD)

**Comment by blood-git** [comment]
That demo man issue can be repeated on many classes which use wearables, some consumable items aswell.

**Comment by MrPanica** [comment]
@RWolfyo, this is a plugin for invitations.

```
#include <sourcemod>
#include <tf2_stocks>
#include <tf2jailredux>
#include <morecolors>

#pragma newdecls required
#pragma semicolon 1

public Plugin myinfo = 
{
	name = "[TF2] Jail Invite",
	author = "Tonki_Ton",
	version = "1.0.0"
};

bool g_bCanUse;

public void OnPluginStart()
{
	RegConsoleCmd("sm_invite", cmd_Invite);

	HookEvent("arena_round_start", ARS);
}

public void ARS(Event hEvent, char[] sName, bool bDontBroadcast)
{
	g_bCanUse = true;
	CreateTimer(20.0, RequstTimeOver); //Time (in seconds) to use the command
}

public Action RequstTimeOver(Handle hTimer)
{
	g_bCanUse = false;
}

public Action cmd_Invite(int iClient, int iArgs)
{
	if (TF2Jail_IsWarden(iClient) && g_bCanUse)
	{
		Menu hMenu = new Menu(SelectClientMenuHandler);

		hMenu.SetTitle("Предложить перейти за охрану\n Выберите Игрока\n ");  //Displayed in the menu

		char sName[64], sUserID[8];

		for (int i = 1; i < MaxClients; i++) if (IsClientInGame(i) && TF2_GetClientTeam(i) == TFTeam_Red)
		{
			IntToString(GetClientUserId(i), sUserID, sizeof(sUserID));
			FormatEx(sName, sizeof(sName), "%N", i);
			hMenu.AddItem(sUserID, sName);
		}

		hMenu.Display(iClient, 30);
	}
	else
	{
		CPrintToChat(iClient, g_bCanUse ? "{crimson}[TF2Jail]{default} Данная команда доступна только командиру!":"{crimson}[TF2Jail]{default} Время на использования команды вышло :("); //Выводится в название если игрок не командир
		return Plugin_Handled;
	}

	return Plugin_Handled;
}

public int SelectClientMenuHandler(Menu hMenu, MenuAction action, int iClient, int iPick)
{
	if (action == MenuAction_End)
		delete hMenu;
	else if (action == MenuAction_Select)
	{
		char sPick[12];

		hMenu.GetItem(iPick, sPick, sizeof(sPick));
		int iPicker = GetClientOfUserId(StringToInt(sPick));

		SendClientMenu(iPicker);
		CPrintToChatAll("{crimson}[TF2Jail]{default} Командир %N пригласил игрока %N в синею команду", iClient, iPicker); //It is displayed when the warden chose whom to invite
	}
}

void SendClientMenu(int iClient)
{
	Menu hMenu = new Menu(ChoiceMenuHandler);

	hMenu.SetTitle("Командир преложил вам перейти за охранну\n "); //Displayed on the menu when you are invited to join.

	hMenu.AddItem(NULL_STRING, "Перейти"); //accept
	hMenu.AddItem(NULL_STRING, "Отказаться"); //Refuse

	hMenu.Display(iClient, 30);
}

public int ChoiceMenuHandler(Menu hMenu, MenuAction action, int iClient, int iPick)
{
	if (action == MenuAction_End)
		delete hMenu;
	else if (action == MenuAction_Select)
	{
		if (iPick == 0)
		{
			if (g_bCanUse)
			{
				TF2_ChangeClientTeam(iClient, TFTeam_Blue);
				TF2_RespawnPlayer(iClient);
				CPrintToChatAll("{crimson}[TF2Jail]{default} Игрок %N принял приглашение командира", iClient); //Displayed to all players when the player agrees to go over the blue.
			}
			else
			{
				CPrintToChat(iClient, "{crimson}[TF2Jail]{default} Время на использование этой команды вышло!"); //Displays if the time to use the command is out
			}
		}
		else if (iPick == 1)
		{
			CPrintToChatAll("{crimson}[TF2Jail]{default} Игрок %N отклонил приглашение командира", iClient); //Displayed to all players when the player refuses to go over the blue.
		}
	}
}
```
