### ISSUE TITLE
Change label: Resolution.

### ISSUE THREAD

**Issue by MrPanica** [Scags/TF2-Jailbreak-Redux#72]
Hello, will you give permission to change the name of the plugin in the search for servers?
In no case do I assign authorship of this plugin to myself, but simply used it as an advertisement for my server. Just some players say that this is disrespect towards you. I did not remove the advertisement in the chat.

![image](https://user-images.githubusercontent.com/44004288/51768950-c3c2aa80-20f2-11e9-98ac-f399f83769ae.png)

**Comment by Scags** [comment]
Of course you can change it. You can do pretty much whatever the hell you want with it (besides trying to sell it for money). :^)

**Comment by MrPanica** [comment]
Thanks for the quick reply to my post!
