### ISSUE TITLE
Random Invulnerability

### ISSUE THREAD

**Issue by Thordin** [Scags/TF2-Jailbreak-Redux#73]
We have people randomly becoming invulnerable. They can be guards or prisoners. It may be related to freeday, but people said they gave free day to 1 person, and someone else became invulnerable.

We don't have any custom last request and we removed the saxton and prophunt lr plugins.

**Comment by RWolfyo** [comment]
had no such problem, r sure it's not something other conflicting?

**Comment by Scags** [comment]
Since there was no follow up on this (plus the fact that this is almost a year old now), I'll be closing it.
