### ISSUE TITLE
SV_StartSound Spam error

### ISSUE THREAD

**Issue by ElPapuh** [Scags/TF2-Jailbreak-Redux#78]
I need help to fix this
![Sin título](https://user-images.githubusercontent.com/26206183/56194161-a1c22f80-6032-11e9-8df2-be2663c634ca.jpg)

**Comment by RWolfyo** [comment]
Duplicate of #68

**Comment by ElPapuh** [comment]
@RWolfyo I know, but I don't see any fix for it, I don't see the music cvar mentioned on #68

**Comment by Scags** [comment]
As of 1.14 this should be fixed. Never once got an instance of it during testing.
