### ISSUE TITLE
Small Request: Disable team change during round.

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#8]
Was wondering if we could disable team change during round as so many people join blu team. Not sure if it does anything as in beginning of round it balances but it's been an eye sore to see like everyone in the server in blu team in middle of round and confuses some players.
Also helps with ghosting too!

**Comment by Scags** [comment]
This doesn't seem like a super duper problem, and there are probably existing plugins out there that can do the same stuff really. As for ghosting, if you're worried about that, you can toggle `tf_gravetalk` to 1 to prevent dead people from do so.

**Comment by unusual917** [comment]
Well usually they join blue team and go with that. If you ever find a plugin for it please let me know :)
I tried looking for one too but can't seem to find it.
