### ISSUE TITLE
How can i disable "sm_tf2jr_criticals" = "2"? 

### ISSUE THREAD

**Issue by Kapkanovski** [Scags/TF2-Jailbreak-Redux#84]
Hello 

So i have this problem that i cannot disable this "sm_tf2jr_criticals" = "0" command i've put it to server cfg as sm_tf2jr_criticals 0 but all i get was unknown command so i created a autoexec.cfg file then but the command in it and in server.cfg writed exec autoexec but the Cvar will again enable the Crits i've tryied to search for that command in files but could not find it anywhere. Can you Help me please?

Thanks Much

Edit: Also i've put the command into console and it worked fine but when  i change the map it will put the original command again (obviously because the command was not saved anywhere)

**Comment by Scags** [comment]
Sure. The plugin creates its own .cfg file when you load it for the first time. It will be under tf/cfg/sourcemod/TF2JailRedux.cfg. There you can find "sm_tf2jr_criticals" somewhere, and you can set it to 0 there.

**Comment by Kapkanovski** [comment]
Oh yes i found it thanks much for fast reply! :-)
