### ISSUE TITLE
BLUs can still be Rebels

### ISSUE THREAD

**Issue by Ketteii** [Scags/TF2-Jailbreak-Redux#86]
BLUs are still marked as rebels once the Rebeller system has been enabled.

Screenshot: https://steamuserimages-a.akamaihd.net/ugc/780729699967542988/19053F1EA71FD35D3CE5F03E4011F5AC0DB3AD4B/

**Comment by Scags** [comment]
Sure I'll take care of this in a sec.

**Comment by Ketteii** [comment]
What files were changed to fix the issue? I'd like to get this on my server, let ya know how it goes. (:

**Comment by Scags** [comment]
TF2Jail_Redux.smx

**Comment by Ketteii** [comment]
Thank you, I'll update and let you know if any issues pop up.
