### ISSUE TITLE
Admin name.

### ISSUE THREAD

**Issue by MrPanica** [Scags/TF2-Jailbreak-Redux#88]
How can I get an admin name that opens or closes cells?
Sometimes admins spam a command, and I need to know which one of them does it.

**Comment by RWolfyo** [comment]
Sourcemod logs??? see who spams the command

**Comment by MrPanica** [comment]
This is not an option.
I have a system of ranks, I almost do not play on the server, but I ensure its operability. I cannot give access to logs to everyone, so I need to see this information directly on the server. I have already remade other commands, such as sm_forcelr, sm_fw, sm_tm, but this command is different from the others and my programming knowledge was not enough for this(

**Comment by Scags** [comment]
There isn't logging in the plugin, yet. This could be something done if I ever get around to Jail Logging #82

**Comment by Scags** [comment]
With V2.0.1Beta, logging for the majority of admin commands is added.
