### ISSUE TITLE
Please allow sm_forcewarden to work without sm_rm first

### ISSUE THREAD

**Issue by unusual917** [Scags/TF2-Jailbreak-Redux#9]
Seems like I can't use sm_forcewarden without having to use sm_removewarden first. I want to use sm_forcewarden with a vote menu plugin on alliedmodders but it doesn't seem to work since it requires sm_rw to execute first.

**Comment by Scags** [comment]
Alrighty, todo

**Comment by unusual917** [comment]
Thank you!
