### ISSUE TITLE
Timer on selecting a warden?

### ISSUE THREAD

**Issue by Ketteii** [Scags/TF2-Jailbreak-Redux#90]
Just another idea that I think TF2Jail had, but unsure.
Instead of being stuck with enabling / disabled instant warden selection, would it be possible to have the plugin select a warden after 5 seconds?

**Comment by Scags** [comment]
Can be done, although the way I'm thinking would separate 'sm_tf2jr_warden_delay' into 2 convars. As setting it to -1 would auto-set a warden directly when the round starts.

**Comment by Scags** [comment]
With V2.0.1 beta, this is added. `sm_tf2jr_warden_delay2` is the cvar for the timer.
