### ISSUE TITLE
can get secondary weapon as prisoner issue

### ISSUE THREAD

**Issue by wonyoungb** [Scags/TF2-Jailbreak-Redux#94]
when the game started announcer counting 5
demoman and soldier can get secondary weapon when they change weapons quickly

**Comment by MrPanica** [comment]
Is this a similar problem?https://github.com/Scags/TF2-Jailbreak-Redux/issues/74

**Comment by bakjinah** [comment]
sort of but not for just demo, It can be any class(secondary weapons glitch)

**Comment by MrPanica** [comment]
Have you tried using my code from that message?

**Comment by Scags** [comment]
I'm almost positive that the last update fixed this problem.
Unless @MrPanica 's code doesn't work 🤠
