### ISSUE TITLE
How can I add new map?

### ISSUE THREAD

**Issue by wonyoungb** [Scags/TF2-Jailbreak-Redux#96]
I just added map with this config but not working well..

	"jb_turbine_v4"
	{
		"CellNames"			"cell_door"
		"CellsButton"		"open_cells"
		"FFButton"			"ff_toggle"
		"Freeday"
		{
			// Consult https://forums.alliedmods.net/showthread.php?t=249606 to get coordinates with ease
			
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-53.89032"
				"Coordinate_Y"		"224.981750"
				"Coordinate_Z"		"48.031250"
			}
		}
		"Warday - Guards"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"-2962.224853"
				"Coordinate_Y"		"-1200.599243"
				"Coordinate_Z"		"-287.968750"
			}
		}
		"Warday - Reds"
		{
			"Teleport"
			{
				"Status"			"1"
				"Coordinate_X"		"3002.025390"
				"Coordinate_Y"		"1328.627685"
				"Coordinate_Z"		"-287.968750"
			}
		}
	}

**Comment by MrPanica** [comment]
Each map maker makes the name of the door in his own way.
You must find out the name of the door on this map.

How do i do this:
Through the GCFScape program, I open the .ent file, in our case jb_turbine_v4.ent.
Then I search for words starting with cell or door.

**Comment by bakjinah** [comment]
how can I convert bsp to ent..?

**Comment by MrPanica** [comment]
A .bsp file is something like an archive, GCFScape opens it.
![image](https://user-images.githubusercontent.com/44004288/66737364-6d5ded80-ee74-11e9-95f9-5ff08ac397eb.png)

**Comment by bakjinah** [comment]
ahh thanks for help worked :D

**Comment by bakjinah** [comment]
can you  please give an example on "jb_turbine_v4" ..?
I tried celldoor,cellbutton,etc but not working..

**Comment by MrPanica** [comment]
I think that this card does not provide for opening doors through the console command.
The cell doors do not open, but break.

**Comment by MrPanica** [comment]
```
"targetname" "cellbutton"
"speed" "5"
"spawnflags" "1537"
"sounds" "0"
"rendermode" "0"
"renderfx" "0"
"rendercolor" "255 255 255"
"renderamt" "255"
"origin" "415 200.5 96"
"movedir" "0 0 0"
"locked_sound" "0"
"locked_sentence" "0"
"lip" "0"
"health" "0"
"disablereceiveshadows" "0"
"classname" "func_button"
"hammerid" "400235"
"OnPressed" "celldoor,Break,,0,-1"
}
{
```
I am not very good at code, but it is clearly visible here that the button acts on celldoor.

**Comment by bakjinah** [comment]
I also tried that code well, but not working.

**Comment by MrPanica** [comment]
> ahh...it's so hard to make new map config sad..I just tried another map but still not working well. 😢

What map?

**Comment by bakjinah** [comment]
ba_jail_snowday.bsp

**Comment by MrPanica** [comment]
> ba_jail_snowday.bsp

"ba_jail_snowday"
	{
		"CellNames"			"ca_celldoors"
	}

**Comment by bakjinah** [comment]
we don't need 
"CellNames"			"cell_door"
	"FFButton"			"ff_toggle"
?

**Comment by MrPanica** [comment]
> we don't need
> "CellNames" "cell_door"
> "FFButton" "ff_toggle"
> ?

The button for opening cameras is usually registered in map and does not require a config.
I do not use the PvP power button, only through the console command.

**Comment by Scags** [comment]
This appears to be resolved, so I'll close it for now.
